/**
 * Signed Trade QR Payload
 *
 * Compact, signed QR for in-person trade handoff with an agent.
 * Lets the agent verify the QR was generated by the actual buyer/provider
 * of the on-chain trade (not a fake QR with a copied tradeId).
 *
 * Layout (binary, fixed size):
 *   4   magic "LDQR"
 *   1   version (1)
 *   1   role (0=buyer, 1=provider)
 *   8   tradeId (u64 LE)
 *   32  publicKey
 *   16  nonce
 *   8   expiresAt (u64 LE, unix seconds)
 *   64  signature (algo-prefix stripped — curve auto-detected at verify)
 *   = 134 bytes → ~180 base64url chars
 *
 * Signing: pjs signRaw wraps the bytes as `<Bytes>...</Bytes>` before signing.
 * @polkadot/util-crypto signatureVerify auto-detects curve and wrap.
 */

import { signatureVerify } from "@polkadot/util-crypto";
import { ethers } from "ethers";
import type { PolkadotSigner } from "polkadot-api";

import { randomBytes } from "./crypto";
import { uint8ArrayToHex } from "./evidence/merkle";

export type TradeQRRole = "buyer" | "provider";

const MAGIC = new Uint8Array([0x4c, 0x44, 0x51, 0x52]); // "LDQR"
const VERSION = 1;
const SIGNED_PREFIX_LEN = 4 + 1 + 1 + 8 + 32 + 16 + 8; // 70 bytes covered by signature
const TOTAL_LEN = SIGNED_PREFIX_LEN + 64; // 134 bytes
const PJS_WRAP_OPEN = new TextEncoder().encode("<Bytes>");
const PJS_WRAP_CLOSE = new TextEncoder().encode("</Bytes>");

const DEFAULT_TTL_SECONDS = 5 * 60;

export interface TradeQRPayload {
  tradeId: bigint;
  role: TradeQRRole;
  publicKey: Uint8Array; // 32 bytes
  nonce: Uint8Array; // 16 bytes
  expiresAt: bigint; // unix seconds
  signature: Uint8Array; // 64 bytes (algo prefix already stripped)
}

function encodeRole(role: TradeQRRole): number {
  return role === "buyer" ? 0 : 1;
}

function decodeRole(byte: number): TradeQRRole {
  if (byte === 0) return "buyer";
  if (byte === 1) return "provider";
  throw new Error(`Invalid role byte: ${byte}`);
}

function writeSignedPrefix(
  view: DataView,
  bytes: Uint8Array,
  payload: Omit<TradeQRPayload, "signature">,
): void {
  let offset = 0;
  bytes.set(MAGIC, offset);
  offset += 4;
  view.setUint8(offset++, VERSION);
  view.setUint8(offset++, encodeRole(payload.role));
  view.setBigUint64(offset, payload.tradeId, true);
  offset += 8;
  bytes.set(payload.publicKey, offset);
  offset += 32;
  bytes.set(payload.nonce, offset);
  offset += 16;
  view.setBigUint64(offset, payload.expiresAt, true);
}

function buildSignedPrefix(
  payload: Omit<TradeQRPayload, "signature">,
): Uint8Array {
  const buffer = new ArrayBuffer(SIGNED_PREFIX_LEN);
  const view = new DataView(buffer);
  const bytes = new Uint8Array(buffer);
  writeSignedPrefix(view, bytes, payload);
  return bytes;
}

function encodePayload(payload: TradeQRPayload): Uint8Array {
  const buffer = new ArrayBuffer(TOTAL_LEN);
  const view = new DataView(buffer);
  const bytes = new Uint8Array(buffer);
  writeSignedPrefix(view, bytes, payload);
  bytes.set(payload.signature, SIGNED_PREFIX_LEN);
  return bytes;
}

function decodePayload(bytes: Uint8Array): TradeQRPayload {
  if (bytes.length !== TOTAL_LEN) {
    throw new Error(
      `Invalid QR length: expected ${TOTAL_LEN} bytes, got ${bytes.length}`,
    );
  }
  for (let i = 0; i < 4; i++) {
    if (bytes[i] !== MAGIC[i]) throw new Error("Invalid QR magic bytes");
  }
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  let offset = 4;
  const version = view.getUint8(offset++);
  if (version !== VERSION) {
    throw new Error(`Unsupported QR version: ${version}`);
  }
  const role = decodeRole(view.getUint8(offset++));
  const tradeId = view.getBigUint64(offset, true);
  offset += 8;
  const publicKey = bytes.slice(offset, offset + 32);
  offset += 32;
  const nonce = bytes.slice(offset, offset + 16);
  offset += 16;
  const expiresAt = view.getBigUint64(offset, true);
  offset += 8;
  const signature = bytes.slice(offset, offset + 64);
  return {
    tradeId,
    role,
    publicKey,
    nonce,
    expiresAt,
    signature,
  };
}

// ─── base64url ───────────────────────────────────────────────────────────────

const B64URL =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
function base64urlEncode(bytes: Uint8Array): string {
  let out = "";
  for (let i = 0; i < bytes.length; i += 3) {
    const b1 = bytes[i] ?? 0;
    const b2 = bytes[i + 1] ?? 0;
    const b3 = bytes[i + 2] ?? 0;
    out += B64URL[b1 >> 2];
    out += B64URL[((b1 & 0x03) << 4) | (b2 >> 4)];
    if (i + 1 < bytes.length) out += B64URL[((b2 & 0x0f) << 2) | (b3 >> 6)];
    if (i + 2 < bytes.length) out += B64URL[b3 & 0x3f];
  }
  return out;
}
function base64urlDecode(str: string): Uint8Array {
  const lookup = new Map<string, number>();
  for (let i = 0; i < B64URL.length; i++) lookup.set(B64URL[i]!, i);
  const out: number[] = [];
  for (let i = 0; i < str.length; i += 4) {
    const c1 = lookup.get(str[i]!);
    const c2 = lookup.get(str[i + 1]!);
    if (c1 === undefined || c2 === undefined) {
      throw new Error("Invalid base64url character");
    }
    out.push((c1 << 2) | (c2 >> 4));
    if (i + 2 < str.length) {
      const c3 = lookup.get(str[i + 2]!);
      if (c3 === undefined) throw new Error("Invalid base64url character");
      out.push(((c2 & 0x0f) << 4) | (c3 >> 2));
      if (i + 3 < str.length) {
        const c4 = lookup.get(str[i + 3]!);
        if (c4 === undefined) throw new Error("Invalid base64url character");
        out.push(((c3 & 0x03) << 6) | c4);
      }
    }
  }
  return new Uint8Array(out);
}

// ─── sign / verify ───────────────────────────────────────────────────────────

function wrapForPjs(data: Uint8Array): Uint8Array {
  const total = PJS_WRAP_OPEN.length + data.length + PJS_WRAP_CLOSE.length;
  const out = new Uint8Array(total);
  out.set(PJS_WRAP_OPEN, 0);
  out.set(data, PJS_WRAP_OPEN.length);
  out.set(PJS_WRAP_CLOSE, PJS_WRAP_OPEN.length + data.length);
  return out;
}

interface SignTradeQROptions {
  tradeId: bigint;
  role: TradeQRRole;
  signer: PolkadotSigner;
  ttlSeconds?: number;
}

/**
 * Build and sign a trade QR. Triggers a host wallet signature popup once
 * (off-chain `<Bytes>` signature, no fee, no chain).
 */
export async function signTradeQR(
  opts: SignTradeQROptions,
): Promise<{ qrString: string; payload: TradeQRPayload }> {
  const ttl = opts.ttlSeconds ?? DEFAULT_TTL_SECONDS;
  const expiresAt = BigInt(Math.floor(Date.now() / 1000) + ttl);
  const nonce = randomBytes(16);
  const publicKey = opts.signer.publicKey;
  if (publicKey.length !== 32) {
    throw new Error(
      `Unsupported signer public key length: ${publicKey.length} (expected 32)`,
    );
  }

  const prefixForSign = buildSignedPrefix({
    tradeId: opts.tradeId,
    role: opts.role,
    publicKey,
    nonce,
    expiresAt,
  });

  // pjs signRaw wraps with <Bytes>...</Bytes> before signing — signatureVerify
  // auto-detects the wrap.
  //
  // Race against a 75s timeout. The host (polkadot-desktop) routes legacy
  // sign requests through Bulletin Paseo to Polkadot Vault on the user's
  // phone; if Vault isn't open, the phone is offline, or the chain follow
  // is stalled, the host's own 60s timeout fires SigningErr — but the
  // host's signingPool is poolSize:1, so a stuck request wedges any
  // queued second one. Bound it slightly above the host so the user sees
  // a clear error instead of an infinite spinner (especially under
  // React StrictMode's double-fire which puts two requests in the queue).
  const SIGN_TIMEOUT_MS = 75_000;
  const rawSig = await Promise.race<Uint8Array>([
    opts.signer.signBytes(prefixForSign),
    new Promise<never>((_, reject) =>
      setTimeout(
        () =>
          reject(
            new Error(
              "Signature timed out. Open Polkadot Vault on your phone and approve the request, then try Generate again.",
            ),
          ),
        SIGN_TIMEOUT_MS,
      ),
    ),
  ]);

  // pjs returns sig as [algo prefix(1), sig(64)]; some signers return raw 64.
  let signature: Uint8Array;
  if (rawSig.length === 65) {
    signature = rawSig.slice(1);
  } else if (rawSig.length === 64) {
    signature = rawSig;
  } else {
    throw new Error(`Unexpected signature length: ${rawSig.length}`);
  }

  const payload: TradeQRPayload = {
    tradeId: opts.tradeId,
    role: opts.role,
    publicKey,
    nonce,
    expiresAt,
    signature,
  };
  const bytes = encodePayload(payload);
  return { qrString: base64urlEncode(bytes), payload };
}

export interface VerifyResult {
  valid: boolean;
  payload?: TradeQRPayload;
  /** EVM h160 address derived from payload publicKey */
  derivedEvmAddress?: string;
  error?: string;
}

/**
 * Decode and cryptographically verify a trade QR string.
 * Returns the EVM h160 address that the caller should compare against
 * `trade.counterparty` (buyer QR) or `trade.locker` (provider QR).
 */
export function verifyTradeQR(qrString: string): VerifyResult {
  let payload: TradeQRPayload;
  try {
    payload = decodePayload(base64urlDecode(qrString));
  } catch (err) {
    return {
      valid: false,
      error: err instanceof Error ? err.message : "Invalid QR data",
    };
  }

  const nowSec = BigInt(Math.floor(Date.now() / 1000));
  if (payload.expiresAt <= nowSec) {
    return { valid: false, payload, error: "QR expired" };
  }

  const prefix = buildSignedPrefix(payload);
  const sigHex = uint8ArrayToHex(payload.signature);
  const pkHex = uint8ArrayToHex(payload.publicKey);

  // signatureVerify auto-tries raw and <Bytes>...</Bytes>-wrapped pre-images
  // and all curves (sr25519/ed25519/ecdsa).
  let result;
  try {
    result = signatureVerify(prefix, payload.signature, payload.publicKey);
  } catch (err) {
    console.warn(
      "[trade-qr] signatureVerify threw:",
      err instanceof Error ? err.message : err,
    );
    return { valid: false, payload, error: "Signature verify threw" };
  }

  if (!result.isValid) {
    const diag = JSON.stringify({
      detected: result.crypto,
      isWrapped: result.isWrapped,
      sigLen: payload.signature.length,
      pubkey: pkHex,
      sig: sigHex,
      msgRaw: uint8ArrayToHex(prefix),
      msgWrapped: uint8ArrayToHex(wrapForPjs(prefix)),
    });
    console.warn(`[trade-qr] signatureVerify rejected ${diag}`);
    return { valid: false, payload, error: "Invalid signature" };
  }

  // Derive EVM h160 from publicKey using the same rule as ss58ToEvmAddress
  // (native account → keccak256(publicKey).slice(-20))
  const derivedEvmAddress =
    "0x" + ethers.keccak256(payload.publicKey).slice(-40);

  return { valid: true, payload, derivedEvmAddress };
}

// ─── helpers for UI ──────────────────────────────────────────────────────────

/**
 * Compare a derived EVM address against a trade participant address.
 * Returns true if they match (case-insensitive). Also handles the case where
 * the trade address is an EVM-derived SS58 (last-12-bytes 0xEE pattern).
 */
export function matchesParticipant(
  derivedEvm: string,
  participantEvm: string,
): boolean {
  return derivedEvm.toLowerCase() === participantEvm.toLowerCase();
}

/**
 * Also try the EVM-derived path: if the participant address came from a pjs
 * account whose AccountId32 is `pubkey[0..20] || 0xEE x 12`, the publicKey
 * embedded in the QR may already BE that AccountId32. Surface that h160 too.
 */
export function alternateEvmFromPubkey(publicKey: Uint8Array): string | null {
  if (publicKey.length !== 32) return null;
  const isEvmDerived = publicKey.slice(20).every((b) => b === 0xee);
  if (!isEvmDerived) return null;
  return (
    "0x" +
    Array.from(publicKey.slice(0, 20))
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("")
  );
}

/**
 * Format the EVM h160 derivation chain so the agent UI can match against
 * either pattern (native sr25519 keccak vs EVM-mapped 0xEE-padded).
 */
export function deriveCandidateEvms(publicKey: Uint8Array): string[] {
  const out: string[] = [];
  out.push("0x" + ethers.keccak256(publicKey).slice(-40));
  const alt = alternateEvmFromPubkey(publicKey);
  if (alt) out.push(alt);
  return out;
}

export const TRADE_QR_TTL_SECONDS = DEFAULT_TTL_SECONDS;
